modLoader="javafml" #mandatory

loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="Public Domain"

issueTrackerURL="" #optional

[[mods]] #mandatory

modId="webdisplays" #mandatory

version="1.0.0" #mandatory

displayName="MCEF" #mandatory

displayURL="https://github.com/Mysticpasta1/webdisplays" #optional

logoFile= "" #optional

credits="" #optional

authors="Mysticpasta1, WaterPicker, Montoyo" #optional

description='''
'''

[[dependencies.webdisplays]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.webdisplays]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"

[[dependencies.webdisplays]]
modId="forgecef"
mandatory=true
versionRange="[1.0.0, )"
ordering="NONE"
side="BOTH"